2024-11-16 21:10:50,231 | INFO | "test_challenge" выполнен успешно
2024-11-16 21:10:50,232 | WARNING | Неверный тип данных для объекта Runner
Имя может быть только строкой, передано int
2024-11-16 21:10:50,233 | WARNING | Traceback (most recent call last):
  File "C:\Users\Администратор\Desktop\PycharmProject\PycharmProjects\PythonProjectUniversity\12\tests_12_4.py", line 81, in test_run
    runner = Runner(2)
             ^^^^^^^^^
  File "C:\Users\Администратор\Desktop\PycharmProject\PycharmProjects\PythonProjectUniversity\12\tests_12_4.py", line 20, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int

2024-11-16 21:10:50,233 | WARNING | Неверная скорость для Runner
Скорость не может быть отрицательной, сейчас -5
2024-11-16 21:10:50,246 | WARNING | Traceback (most recent call last):
  File "C:\Users\Администратор\Desktop\PycharmProject\PycharmProjects\PythonProjectUniversity\12\tests_12_4.py", line 70, in test_walk
    runner = Runner("Вася", -5)
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\Desktop\PycharmProject\PycharmProjects\PythonProjectUniversity\12\tests_12_4.py", line 25, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5

